name: Download and Export File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file
        run: |
          curl -L -o google_devices-oriole-tq2a.230505.002-9d23e4ab.tgz https://googledownloads.cn/dl/android/aosp/google_devices-oriole-tq2a.230505.002-9d23e4ab.tgz

      - name: Export downloaded file
        uses: actions/upload-artifact@v2
        with:
          name: google_devices-oriole-tq2a.230505.002-9d23e4ab
          path: google_devices-oriole-tq2a.230505.002-9d23e4ab.tgz
